version: "3.8"

services:
  registry:
    restart: always
    image: registry:2.8.3
    container_name: registry
    ports: 
      - 5000:5000
      - 443:443
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:443
      REGISTRY_HTTP_TLS_CERTIFICATE: /certs/registry.mily.local.crt
      REGISTRY_HTTP_TLS_KEY: /certs/registry.mily.local.key
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry/
    volumes:
      - /certs:/certs
      - /registry/:/registry/
